### ISSUE TITLE
User did not grant permission. on window7(64) and Electron4.0.2

### ISSUE THREAD

**Issue by anbang** [jorangreef/sudo-prompt#102]
User did not grant permission. on window7(64) and Electron4.0.2

- window7(64) 
- Electron4.0.2

```
Error: User did not grant permission.
at D:\test_anbang\demo1\node_modules\sudo-prompt\index.js:534:29
at ChildProcess.exithandler (child_process.js:306:5)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

## run `node_modules\sudo-prompt\test.js`

```
D:\test_anbang\demo1\node_modules\sudo-prompt>node test.js
sudo.exec("echo %SUDO_PROMPT_TEST_ENV%", {"env":{"SUDO_PROMPT_TEST_ENV":"hello w
orld"},"name":"Electron"})
error: Error: User did not grant permission.
    at D:\test_anbang\demo1\node_modules\sudo-prompt\index.js:534:29
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
stdout: undefined
stderr: undefined
D:\test_anbang\demo1\node_modules\sudo-prompt\test.js:52
            if (error) throw error;
                       ^

Error: User did not grant permission.
    at D:\test_anbang\demo1\node_modules\sudo-prompt\index.js:534:29
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```

**Comment by anbang** [comment]
Has anyone encountered the same problem? please help

**Comment by anbang** [comment]
this issues is solved, 

because `powershell` does not exist or is not added to the computer path

`sudo-prompt`  really works is

```
powershell.exe Start-Process -FilePath "'C:\Users\ADMINI~1\AppData\Local\Temp\3d6f61aa7a8b39caebc1803e8c57662a\execute.bat'" -WindowStyle hidden -Verb runAs
```
computer if not has `powershell.exe`, You will receive an error;

**Comment by jorangreef** [comment]
Thanks @anbang 

PowerShell is required. Would you like to close this issue?
