### ISSUE TITLE
Incompatible under Chinese/Japanese/Korean

### ISSUE THREAD

**Issue by anbang** [jorangreef/sudo-prompt#103]
## Incompatible under Chinese/Japanese/Korean

The computer I tested is based on windows10

run `node_modules\sudo-prompt\test.js`

I got the information below

```
PS F:\anbang_test\sudo-demo\node_modules\sudo-prompt> node .\test.js
sudo.exec("echo %SUDO_PROMPT_TEST_ENV%", {"env":{"SUDO_PROMPT_TEST_ENV":"hello world"},"name":"Electron"})
uuid 678e17538c9a26a73ca459e9103fd5af
temp C:\Users\回收\AppData\Local\Temp
WindowsWriteExecuteScript instance.pathExecute C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\execute.bat
command powershell.exe Start-Process -FilePath "'C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\execute.bat'" -WindowStyle hidden -Verb runAs
end.. error Error: User did not grant permission.
    at F:\anbang_test\sudo-demo\node_modules\sudo-prompt\index.js:609:39
    at FSReqWrap.oncomplete (fs.js:153:21)
end.. stdout undefined
end.. stderr undefined
C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af
error: undefined
stdout: undefined
stderr: undefined
F:\anbang_test\sudo-demo\node_modules\sudo-prompt\test.js:54
              throw new Error('stdout != ' + JSON.stringify(expected));
              ^

Error: stdout != "hello world\r\n"
    at F:\anbang_test\sudo-demo\node_modules\sudo-prompt\test.js:54:21
    at kill (F:\anbang_test\sudo-demo\node_modules\sudo-prompt\test.js:7:44)
    at F:\anbang_test\sudo-demo\node_modules\sudo-prompt\test.js:50:9
    at end (F:\anbang_test\sudo-demo\node_modules\sudo-prompt\index.js:485:13)
    at F:\anbang_test\sudo-demo\node_modules\sudo-prompt\index.js:509:45
    at F:\anbang_test\sudo-demo\node_modules\sudo-prompt\index.js:609:35
    at FSReqWrap.oncomplete (fs.js:153:21)
PS F:\anbang_test\sudo-demo\node_modules\sudo-prompt>

```

## modify XXXX/execute.bat

modify file:`C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\execute.bat`

```
@echo off
call "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\command.bat" > "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stdout" 2> "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stderr"
(echo %ERRORLEVEL%) > "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\status"
```

To

```
echo
call "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\command.bat" > "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stdout" 2> "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stderr"
(echo %ERRORLEVEL%) > "C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\status"
```

## modify XXXX/command.bat

```
@echo off
chcp 65001>nul
cd /d "F:\anbang_test\sudo-demo\node_modules\sudo-prompt"
set SUDO_PROMPT_TEST_ENV=hello world
echo %SUDO_PROMPT_TEST_ENV%
```
To

```
echo
chcp 65001>nul
cd /d "F:\anbang_test\sudo-demo\node_modules\sudo-prompt"
set SUDO_PROMPT_TEST_ENV=hello world
echo %SUDO_PROMPT_TEST_ENV%
```

## run `execute.bat`

```
C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af>call "C:\Users\鍥炴敹\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\command.bat"  1>"C:\Users\鍥炴敹\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stdout" 2>"C:\Users\鍥炴敹\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\stderr"
系统找不到指定的路径。

C:\Users\回收\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af>(echo 9009 ) 1>"C:\Users\鍥炴敹\AppData\Local\Temp\678e17538c9a26a73ca459e9103fd5af\status"
系统找不到指定的路径。
```

> Computer username is not correct;
> hope:回收
> reality:鍥炴敹

# The reason

Windows` .bat` files are best used `ANSI`;

`sudo-prompt` use `utf-8`,

```
 Node.fs.writeFile(instance.pathCommand, script, 'utf-8', end);
```

 Will receive an error message ( under Chinese/Japanese/Korean)

Hi jorangreef ,Can you fix this?  @jorangreef

**Comment by jorangreef** [comment]
Thanks @anbang could you modify those same files, but in a way that passes the `test.js` script?

**Comment by anbang** [comment]
Thanks @jorangreef 

I am running `node_modules\sudo prompt\test.js`

Error message

```
Error: User has not granted permission.
```

In order to locate where the error occurred

I modified the `C:\Users\回收\AppData\Local\Temp\XXXXXXXXXXXXX\execute.bat` file to open the echo info;

I found that when the computer uses Chinese as the user name, the `.bat` file written in the `UTF8` format does not work properly.

**Comment by jorangreef** [comment]
Thanks @anbang I understand.

Now, would you please try and modify the same file, but this time, modify it so that the test works correctly?

In other words, instead of modifying to see what's going wrong, modify to see how it can be fixed?

**Comment by jorangreef** [comment]
@anbang if you can help with a fix that would be great, but I am closing for now.
