### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by ghostbar** [jorangreef/sudo-prompt#3]
I'm doing a `sudo.exec('echo a name', function (err) {console.log(err)})` and keep getting the same error without any prompt being shown.

```
Error: Command failed: /bin/sh -c sudo -n echo 'en2'
sudo: a password is required

sudo: a password is required

    at ChildProcess.exithandler (child_process.js:209:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Mac 10.10.5
process.env['USER'] is defined
os.tmpdir() is writable by the user

You can see the issue on https://github.com/ghostbar/shakeitoff

EDIT: Already tried setting the title name, as well.

**Comment by jorangreef** [comment]
Thanks @ghostbar.

Fixed in https://github.com/jorangreef/sudo-prompt/commit/1698b7384177ca40c038af36c3c05e504fdaff06.
