### ISSUE TITLE
Error: Platform not yet supported. on Arch Linux

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jorangreef/sudo-prompt#82]
```
Error: Platform not yet supported.
    at Object.Sudo [as exec] (/home/spaceboyross/OS.js/src/packages/osjs-linux-installer-application/node_modules/sudo-prompt/index.js:21:7)
    at Object.call (/home/spaceboyross/OS.js/src/packages/osjs-linux-installer-application/node_modules/sudo-fn/index.js:36:15)
    at repl:1:6
    at Script.runInThisContext (vm.js:122:20)
    at REPLServer.defaultEval (repl.js:333:29)
    at bound (domain.js:395:14)
    at REPLServer.runBound [as eval] (domain.js:408:12)
    at REPLServer.onLine (repl.js:640:10)
    at REPLServer.emit (events.js:194:15)
    at REPLServer.EventEmitter.emit (domain.js:441:20)
```

* `process.platform`: `"Linux"`

**Comment by jorangreef** [comment]
What is the exact output of `process.platform`?

`Linux` or `linux`?

**Comment by jorangreef** [comment]
Are you modifying Node's `process` object somewhere in your code?

**Comment by SpaceboyRoss01** [comment]
No18.12.2018, 00:42, "Joran Dirk Greef" <notifications@github.com>:Are you modifying Node's process object somewhere in your code?

**Comment by jorangreef** [comment]
@SpaceboyRoss01 your comment did not come through properly. Please try replying directly on GitHub.

**Comment by SpaceboyRoss01** [comment]
I said that I'm not modifying node's `process` object.

**Comment by jorangreef** [comment]
`process.platform` should be `linux` but your first comment shows `Linux`.

We compare the platform string case-sensitively. I'm not sure why you're getting `Linux` as your platform instead of `linux`.

If you can provide more information, or suggest a way to add support, then please re-open.
